; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
board_microros_transport = wifi
lib_deps = 
	adafruit/Adafruit BusIO@^1.14.0
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	adafruit/Adafruit SSD1306@^2.5.7
	https://gitee.com/ohhuo/micro_ros_platformio.git
	https://github.com/fishros/Esp32McpwmMotor.git
	https://github.com/fishros/Esp32PcntEncoder.git
	adafruit/Adafruit_VL53L0X@^1.2.5
build_flags = 
	-D MPU6050_USE_I2C
	-D RCLC_MAX_SUBSCRIBERS=1
	-D RCLC_MAX_PUBLISHERS=2
	-D RCLC_MAX_TIMERS=0
	-DCONFIG_FREERTOS_HZ=1000
	-D M_PI=3.14159265358979323846
monitor_speed = 115200
build_dir = .pio/build_featheresp32
